<?php
/**
 * Seubra functions and definitions
 * @since seubra 1.0
 */

/* HSTS - Only HTTPS connections */
header('Strict-Transport-Security: max-age=31536000;');

if ( ! function_exists( 'seubra_setup' ) ) :
    function seubra_setup() {

        add_theme_support( 'automatic-feed-links' );

        add_theme_support( 'title-tag' );

        add_theme_support( 'post-thumbnails' );

        add_theme_support( 'html5', array(
            'search-form',
            'comment-form',
            'comment-list',
            'gallery',
            'caption',
        ) );

        add_theme_support( 'custom-logo', array(
            'height'      => 560,
            'width'       => 220,
            'flex-width'  => true,
            'flex-height' => true,
        ) );

        // Add theme support for selective refresh for widgets.
        add_theme_support( 'customize-selective-refresh-widgets' );
        // Add support for full and wide align images.
        add_theme_support( 'align-wide' );
        // Add support for editor styles.
        add_theme_support( 'editor-styles' );
        // Enqueue editor styles.
        add_editor_style( 'style-editor.css' );
        // Add support for responsive embedded content.
        add_theme_support( 'responsive-embeds' );
        remove_theme_support( 'wc-product-gallery-zoom' );
        remove_theme_support( 'wc-product-gallery-lightbox' );
        remove_theme_support( 'wc-product-gallery-slider' );
    }
endif;
add_action( 'after_setup_theme', 'seubra_setup' );

add_theme_support( 'menus' );


function theme_register_nav_menu() {
    register_nav_menu( 'top', 'Header Menu' );
    register_nav_menu( 'footer', 'Footer Menu' );
}

add_action( 'after_setup_theme', 'theme_register_nav_menu' );

@ini_set( 'upload_max_size' , '120M' );
@ini_set( 'post_max_size', '120M');
@ini_set( 'max_execution_time', '300' );

function remove_from_admin_bar($wp_admin_bar) {
    /*
     * Placing items in here will only remove them from admin bar
     * when viewing the fronte end of the site
    */
    if ( ! is_admin() ) {
        // Example of removing item generated by plugin. Full ID is #wp-admin-bar-si_menu
        $wp_admin_bar->remove_node('si_menu');

        // WordPress Core Items (uncomment to remove)
        $wp_admin_bar->remove_node('updates');
        $wp_admin_bar->remove_node('comments');
        $wp_admin_bar->remove_node('new-content');
        $wp_admin_bar->remove_node('wp-logo');
        $wp_admin_bar->remove_node('customize');
    }

    /*
     * Items placed outside the if statement will remove it from both the frontend
     * and backend of the site
    */
    $wp_admin_bar->remove_node('wp-logo');
}

add_action('admin_bar_menu', 'remove_from_admin_bar', 999);


/**
 * Proper way to enqueue scripts and styles
 */
function seubra_scripts() {
    wp_enqueue_style( 'header_style', get_template_directory_uri() . '/css/header.css', array(), null );
    wp_enqueue_style( 'main_style', get_template_directory_uri() . '/css/main.css' );
    wp_enqueue_style( 'base_style', get_template_directory_uri() . '/style.css' );
    wp_enqueue_script( 'custom-script', get_template_directory_uri() . '/scripts/app.js', array( 'jquery' ) );
}

add_action( 'wp_enqueue_scripts', 'seubra_scripts' );


function seubra_login_stylesheet() {
    wp_enqueue_style( 'custom-login', get_stylesheet_directory_uri() . '/css/style-login.css' );
//  wp_enqueue_script( 'custom-login', get_stylesheet_directory_uri() . '/style-login.js' );
}

add_action( 'login_enqueue_scripts', 'seubra_login_stylesheet' );


/**
 * Filter function used to remove the tinymce emoji plugin.
 *
 * @param array $plugins
 *
 * @return array Difference betwen the two arrays
 */
function disable_emojis_tinymce( $plugins ) {
    if ( is_array( $plugins ) ) {
        return array_diff( $plugins, array( 'wpemoji' ) );
    } else {
        return array();
    }
}

/**
 * Remove emoji CDN hostname from DNS prefetching hints.
 *
 * @param array $urls URLs to print for resource hints.
 * @param string $relation_type The relation type the URLs are printed for.
 *
 * @return array Difference betwen the two arrays.
 */
function disable_emojis_remove_dns_prefetch( $urls, $relation_type ) {
    if ( 'dns-prefetch' == $relation_type ) {
        /** This filter is documented in wp-includes/formatting.php */
        $emoji_svg_url = apply_filters( 'emoji_svg_url', 'https://s.w.org/images/core/emoji/2/svg/' );

        $urls = array_diff( $urls, array( $emoji_svg_url ) );
    }

    return $urls;
}

/**
 * Acf options page
 */
if ( function_exists( 'acf_add_options_page' ) ) {
    acf_add_options_page();
}


add_filter( 'login_headerurl', create_function( '', 'return get_home_url();' ) );
add_filter( 'login_headertitle', create_function( '', 'return false;' ) );

function seubra_enable_root_relative_urls() {
    return ! ( is_admin() && in_array( $GLOBALS['pagenow'], array(
                'wp-login.php',
                'wp-register.php'
            ) ) ) && current_theme_supports( 'root-relative-urls' );
}

function my_acf_init() {
    acf_update_setting( 'google_api_key', 'AIzaSyDxbeVVdNPUe8WZxM5sY69Oug7ol0ZeD6o' );
}

add_action( 'acf/init', 'my_acf_init' );